version: '3.5'

services:

  apache:
    build:
      context: docker/nginx/.
    container_name: ${LARAVEL_CONTAINER_NAME}
    ports:
      - ${LARAVEL_PORT}:80
    volumes:
      - ./src/:/var/www/html/
    networks:
      backend:
        aliases:
          - ${LARAVEL_CONTAINER_NAME}
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
     - ${MYSQL_PORT}:3306
    command: --authentication_policy=mysql_native_password
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=homestead
     - MYSQL_USER=homestead
     - MYSQL_PASSWORD=secret
    volumes:
      - ./data:/var/lib/mysql
    networks:
      backend:
        aliases:
          - ${MYSQL_CONTAINER_NAME}

networks:
  backend:
    name: ${NETWORK_NAME}